name: 'marketing_analytics_platform'
version: '1.0.0'
config-version: 2

profile: 'marketing_analytics_platform'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_analytics_platform:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
